# Generated by Django 5.0.6 on 2024-06-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentregistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('RollNo', models.IntegerField()),
                ('Father_Name', models.CharField(max_length=255)),
                ('Mother_Name', models.CharField(max_length=255)),
                ('Class', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Fees', models.IntegerField()),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=255)),
                ('Semester_Year', models.DurationField()),
                ('Profile', models.ImageField(upload_to=True)),
                ('Pro_image', models.URLField()),
                ('Branch', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'StudentInfo',
            },
        ),
    ]
