# Generated by Django 5.0.6 on 2024-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='Branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='Class',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='Father_Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='Fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='Gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='Mother_Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='Pro_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='Profile',
            field=models.ImageField(null=True, upload_to=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='RollNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='Semester_Year',
            field=models.DurationField(null=True),
        ),
    ]
